version: 2    
updates:
  - directory: /
    exclude-paths: ["/content/"]
    package-ecosystem: nuget
    schedule:
      interval: daily
  - directory: /
    exclude-paths: ["/content/"]
    package-ecosystem: github-actions
    schedule:
      interval: daily
  # distinct groups so that PRs will clearly indicate if the update is for the template package, or the template content
  - directory: /content/
    package-ecosystem: nuget
    ignore:
      - dependency-name: HarmonyX
    schedule:
      interval: daily
  - directory: /content/
    package-ecosystem: github-actions
    schedule:
      interval: daily